### ISSUE TITLE
tfx.utils.dsl_utils isn't supported anymore and raises errors.

### ISSUE THREAD

**Issue by TimoKerr** [Building-ML-Pipelines/building-machine-learning-pipelines#55]
Hi there,

I tried to follow along, and at the very start where we are to ingest a local csv-file, we have to 
```from tfx.utils.dsl_utils import external_input```, and use it to pass the external data_dir to ```CsvExampleGen```. However, this does not work anymore. It would be nice to update this. Currently, TFX suggest passing the data_dir directly as a string. However, even though this does not raise an error, it fails to ingest the .csv file. As to how to do it properly, I've posted a question on the brand new Tensorflow forum: https://discuss.tensorflow.org/t/tfx-csvexamplegen-does-not-work-with-simply-example-help/1589

Hope this can be resolved :)
Best,
Timo

**Comment by hanneshapke** [comment]
Hi @TimoKerr,

Thank you for reporting this issue.
Check out the latest updates to the example code: https://github.com/Building-ML-Pipelines/building-machine-learning-pipelines/releases/tag/examples_based_on_tfx_1.4

The issue should be fixed with the latest update. Please reopen if you run into trouble.
Thank you again for reporting the issue.

- Hannes
